language: python

os:
- linux
#- windows
#- osx

python:
- "2.6"
- "2.7"
- "3.3"
- "3.4"
- "3.5"
- "3.6"

script:
- python -m pytest vasp tests --cov=vasp

install:
- pip install setuptools
- pip install python-coveralls
- pip install pytest
- pip install pytest-cov
- pip install .

after_success:
- coveralls
- mkdir docs
- echo hello world > docs/index.html

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs
  #github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  on:
    branch: master
