language: python
os:
- linux
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
script:
- python -m pytest vasp tests --cov=vasp
install:
- pip install setuptools
- pip install python-coveralls
- pip install pytest
- pip install pytest-cov
- pip install .
- if [[ ! $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pip install sphinx; fi
after_success:
- coveralls
- cd docs
- if [[ ! $TRAVIS_PYTHON_VERSION = 2.6 ]]; then make html; fi
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs/build/html/
  keep-history: false
  on:
    repo: alejandrogallo/python-vasp
  github-token: $GITHUB_TOKEN
