language: python
os:
- linux
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
script:
- python -m pytest vasp tests --cov=vasp
install:
- pip install setuptools
- pip install python-coveralls
- pip install pytest
- pip install pytest-cov
- pip install .
after_success:
- coveralls
- mkdir docs
- echo hello world > docs/index.html
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs
  keep-history: false
  on:
    repo: alejandrogallo/python-vasp
  github-token:
    secure: DKDApgczF8bPmoVgMMN0D8ml22VLvrEhxFgQpjaQ+QYR+WVwhl9Xzu+bIqf86PSVb8e5XfFGSdD39LSBUoIU9x4BCU1gIxT4RNRoHCx1HQMxFX7qhxwHHaI6eUg/BE4RhC9/g7QlRfy4yW9qEkpS5WDqEXZxq03acwWZrlaat3829b8waJQdDV1/YR7O7LRlT/xUBUYKk+3UWb0c/fZwCLkr2DlZ9heCnoSRSLp0S1kSuqPv4kD9Q3AGVQg6ASyxamV2cNsqOnKLSp22st2vja5PJYZOA5ofy/CqOlJSnG/zMtsiPF0glWXVYFQZU+1DtNN5o/W7SFeFlP3Vuh6V4QvDGum7UNbi8e7F0xM3iee1uY9ENo2XNTWK26nlKSr7q/KcrC2R9Cw7Tka1bSHUmVWp3ENjgSrq5hW8l5obE9G6gSyR8v6q98D8HpjYRaS4/pAn36eS++G8o6yszZ04A7f3XuTM5ECvCJyD8FbA6OaEihHwTGJD+DnCiuBYb9ErhRueJblV/wfqCszKVegiWV4by+iOaArYeyGqJwaL7KQOp7wMxI93HqkyWratmYlZ6wJaCxMW2idTo6Dxy9el8sMnsLKf4t9BAlP589ikfTR933XV89495+DTRntpPZOKSCHYcTGwKWnwx8KF6OJDMyMnmAvXE8M9mto0vcAFbek=
